version: '3.0'
services:
 unifi-controller:
   image: jacobalberty/unifi:latest
   volumes:
     - '/mnt/unifi_data/:/var/lib/unifi'
     - '/mnt/unifi_data/:/var/log/unifi'
     - '/mnt/unifi_data/:/var/run/unifi'
   ports:
     - '3478:3478/udp'
     - '10001:10001/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
   network_mode: host
   environment:
     - TZ=Sydney/Australia
   labels:
     - 'unifi-controller'
